#!/usr/bin/env bash

set -euo pipefail

repo_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
cd "$repo_dir"

# Pin the tools that are not available from Amazon Linux's enabled dnf repos.
# scdoc output changes between versions, so pinning keeps the committed man
# page stable when the pre-commit hook rebuilds it.
scdoc_version=1.11.5
scdoc_sha256=98780bbdf16c1bce89ef3a8c0f537ac6e4ea77087b609e7698857614488a2a62
shellcheck_version=0.9.0
shellcheck_sha256=700324c6dd0ebea0117591c6cc9d7350d9c7c5c287acbad7630fa17b1d4d9e2f

# Enable the checked-in pre-commit hook that keeps whoport.1 in sync with
# whoport.1.scd; Git does not enable repository hooks automatically.
git config core.hooksPath .githooks

case "$(uname -s)" in
Darwin)
  command -v brew >/dev/null || {
    echo "setup: Homebrew is required on macOS" >&2
    exit 1
  }
  brew bundle --file Brewfile
  echo "setup: ready"
  ;;
Linux)
  command -v dnf >/dev/null || {
    echo "setup: Linux setup currently supports dnf-based systems" >&2
    exit 1
  }

  mapfile -t dnf_packages < <(
    sed -E 's/[[:space:]]*#.*//; /^[[:space:]]*$/d' dnf-packages.txt
  )
  sudo dnf install -y "${dnf_packages[@]}"

  tmp=$(mktemp -d)
  trap 'rm -rf "$tmp"' EXIT

  download_verified() {
    local url=$1 expected_sha256=$2 output=$3

    curl -fsSL "$url" -o "$output"
    printf '%s  %s\n' "$expected_sha256" "$output" |
      sha256sum --check --status
  }

  installed_scdoc_version=$(
    if command -v scdoc >/dev/null; then
      printf 'x(1)\n\n# NAME\n\nx - y\n' |
        scdoc |
        sed -n 's/^\.\\\" Generated by scdoc //p'
    fi
  )
  if [ "$installed_scdoc_version" != "$scdoc_version" ]; then
    download_verified \
      "https://git.sr.ht/~sircmpwn/scdoc/archive/$scdoc_version.tar.gz" \
      "$scdoc_sha256" \
      "$tmp/scdoc.tar.gz"
    tar -xzf "$tmp/scdoc.tar.gz" -C "$tmp"
    make -s -C "$tmp/scdoc-$scdoc_version" LDFLAGS=
    sudo install -m 0755 "$tmp/scdoc-$scdoc_version/scdoc" /usr/local/bin/scdoc
  fi

  if ! command -v shellcheck >/dev/null; then
    download_verified \
      "https://github.com/koalaman/shellcheck/releases/download/v$shellcheck_version/shellcheck-v$shellcheck_version.linux.x86_64.tar.xz" \
      "$shellcheck_sha256" \
      "$tmp/shellcheck.tar.xz"
    tar -xJf "$tmp/shellcheck.tar.xz" -C "$tmp"
    sudo install -m 0755 "$tmp/shellcheck-v$shellcheck_version/shellcheck" /usr/local/bin/shellcheck
  fi

  echo "setup: ready"
  ;;
*)
  echo "setup: no dependency installer for $(uname -s)" >&2
  exit 1
  ;;
esac
